### PR TITLE
patches to:

### PR DESCRIPTION
**Pull request by Ironholds**
1. Replace a difficult-to-read if(){}else(){} statement with a call to ifelse();
2. Standardise formatting for control flows (multiple conventions were being used);
3. expand non-descriptive object names (fl, f, p) to descriptive ones (writer_list, event_writer, parent)

Love this package thus far! Would it be useful for me to start throwing in unit tests?

### CODE REVIEW

**Comment by Ironholds** [comment]
Oop; conflicting merge. Want me to amend to factor in the e <- .GlobalEnv change and resubmit?

**Comment by smbache** [comment]
That'd probably be easier! Go ahead, and I'll merge.

But be aware, that I realised that activation of the handlers only works in interactive mode.
I tried to make a script, and source it, and no logging was done... Not sure how to fix it so far...

**Comment by Ironholds** [comment]
Hmn. Obvious question is obvious, but: have you tried a hidden self-contained environment assigned to the global namespace?

**Comment by smbache** [comment]
No; not sure what you are suggesting? That work for you?

**Comment by Ironholds** [comment]
Not tried it; I'll experiment at my end and see what I can get to work :).

**Comment by smbache** [comment]
Nice; I won't have time more tonight (here it's late(ish)), so I'll just hope you fixed it for tomorrow ;)

**Comment by Ironholds** [comment]
So, for me, it works with both source() and R CMD BATCH. See [this gist](https://gist.github.com/Ironholds/55c69f7b75032155c35e)

**Comment by smbache** [comment]
Would be great. Have to try again when at computer. Maybe my session was ill.

**Pull request closed without merging**
